// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/github': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/github.get').default>>>>
    }
    '/api/todos/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/[id].patch').default>>>>
    }
    '/api/todos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/index.post').default>>>>
    }
    '/api/todos/stats': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/stats').default>>>>
    }
    '/api/_hub/**:feature': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3.2_drizzle-orm@0.44.2_@cloudflare+workers-types@4.20250617.0_09ebf67edf4647f03c4487e7bae46639/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/[...feature]').default>>>>
    }
    '/api/_hub': {
      'head': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3.2_drizzle-orm@0.44.2_@cloudflare+workers-types@4.20250617.0_09ebf67edf4647f03c4487e7bae46639/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/index.head').default>>>>
    }
    '/api/_hub/manifest': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3.2_drizzle-orm@0.44.2_@cloudflare+workers-types@4.20250617.0_09ebf67edf4647f03c4487e7bae46639/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/manifest.get').default>>>>
    }
    '/api/_hub/sync-variables': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3.2_drizzle-orm@0.44.2_@cloudflare+workers-types@4.20250617.0_09ebf67edf4647f03c4487e7bae46639/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/sync-variables.post').default>>>>
    }
    '/api/_hub/database/:command': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3.2_drizzle-orm@0.44.2_@cloudflare+workers-types@4.20250617.0_09ebf67edf4647f03c4487e7bae46639/node_modules/@nuxthub/core/dist/runtime/database/server/api/_hub/database/[command].post').default>>>>
    }
    '/api/_hub/database/query': {
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3.2_drizzle-orm@0.44.2_@cloudflare+workers-types@4.20250617.0_09ebf67edf4647f03c4487e7bae46639/node_modules/@nuxthub/core/dist/runtime/database/server/api/_hub/database/query.options').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3.2_drizzle-orm@0.44.2_@cloudflare+workers-types@4.20250617.0_09ebf67edf4647f03c4487e7bae46639/node_modules/@nuxthub/core/dist/runtime/database/server/api/_hub/database/query.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@3.17.5_@parcel+watcher@2.4.1_@types+node@22.1.0_db0@0.3.2_drizzle-orm@0.44.2_@clou_27b39a761d29105b1fed7f90fdbccc63/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@1.13.0_magicast@0.3.5_vite@6.3.5_@types+node@22.1.0_jiti@2.4.2_lightningcss@_2590b93d6d9281914d1108078ed1f5f0/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/api/_auth/session': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-auth-utils@0.5.20_magicast@0.3.5/node_modules/nuxt-auth-utils/dist/runtime/server/api/session.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-auth-utils@0.5.20_magicast@0.3.5/node_modules/nuxt-auth-utils/dist/runtime/server/api/session.get').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}