// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/auth/github': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/github.get').default>>>>
    }
    '/api/todos/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/[id].patch').default>>>>
    }
    '/api/todos': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/index.post').default>>>>
    }
    '/api/todos/stats': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/todos/stats').default>>>>
    }
    '/api/_hub/**:feature': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3.2_drizzle-orm@0.44.2_@cloudflare+workers-types@4.20250905.0_8c8bd710d6178867391147f6595be40a/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/[...feature]').default>>>>
    }
    '/api/_hub': {
      'head': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3.2_drizzle-orm@0.44.2_@cloudflare+workers-types@4.20250905.0_8c8bd710d6178867391147f6595be40a/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/index.head').default>>>>
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3.2_drizzle-orm@0.44.2_@cloudflare+workers-types@4.20250905.0_8c8bd710d6178867391147f6595be40a/node_modules/@nuxthub/core/dist/runtime/cors.dev').default>>>>
    }
    '/api/_hub/manifest': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3.2_drizzle-orm@0.44.2_@cloudflare+workers-types@4.20250905.0_8c8bd710d6178867391147f6595be40a/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/manifest.get').default>>>>
    }
    '/api/_hub/sync-variables': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3.2_drizzle-orm@0.44.2_@cloudflare+workers-types@4.20250905.0_8c8bd710d6178867391147f6595be40a/node_modules/@nuxthub/core/dist/runtime/base/server/api/_hub/sync-variables.post').default>>>>
    }
    '/api/_hub/database/:command': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3.2_drizzle-orm@0.44.2_@cloudflare+workers-types@4.20250905.0_8c8bd710d6178867391147f6595be40a/node_modules/@nuxthub/core/dist/runtime/database/server/api/_hub/database/[command].post').default>>>>
    }
    '/api/_hub/database/query': {
      'options': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3.2_drizzle-orm@0.44.2_@cloudflare+workers-types@4.20250905.0_8c8bd710d6178867391147f6595be40a/node_modules/@nuxthub/core/dist/runtime/database/server/api/_hub/database/query.options').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxthub+core@0.9.0_db0@0.3.2_drizzle-orm@0.44.2_@cloudflare+workers-types@4.20250905.0_8c8bd710d6178867391147f6595be40a/node_modules/@nuxthub/core/dist/runtime/database/server/api/_hub/database/query.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt@4.1.0_@parcel+watcher@2.5.1_@vue+compiler-sfc@3.5.21_db0@0.3.2_drizzle-orm@0.44.2__b637849a2d9c17a2791e03a42783086c/node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/@nuxt+icon@1.15.0_magicast@0.3.5_vite@7.1.4_jiti@2.5.1_lightningcss@1.30.1_terser@5.44._95934c3fc74df3d138a84eb210252c6b/node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/api/_auth/session': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-auth-utils@0.5.24_magicast@0.3.5/node_modules/nuxt-auth-utils/dist/runtime/server/api/session.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/.pnpm/nuxt-auth-utils@0.5.24_magicast@0.3.5/node_modules/nuxt-auth-utils/dist/runtime/server/api/session.get').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}